#!/usr/bin/env bash
set -euo pipefail
# Author: Mark Raysmith <raysmith.subs@gmail.com>
# Date: 2026-08-08
source "$(dirname "$0")/spark-compose-common.sh"

# Resolves the pinned Spark runtime artifacts into the image build context and
# writes the lock manifest.
#
# This prepares an image build; it never runs one. P1-0.1 keeps image
# assembly out of the harness, so the operator runs docker build themselves
# and the command is printed at the end.
#
# The Hadoop client jars the Spark distribution already ships are excluded in
# the resolver POM rather than deleted afterwards, because a second copy of
# hadoop-common over the runtime is the ABI mismatch spark_compute.md refuses
# to paper over.

image_dir="$REPO_DIR/platform/spark/image"
jar_dir="$image_dir/jars"
lock_file="$image_dir/artifact-lock.txt"

rm -rf "$jar_dir"
mkdir -p "$jar_dir"

log "Resolving the pinned Spark runtime artifacts with the repository toolchain"
(cd "$REPO_DIR" && ./mvnw --quiet --file platform/spark/image/pom.xml \
  dependency:copy-dependencies \
  -DincludeScope=runtime \
  -DoutputDirectory="$jar_dir")

shopt -s nullglob
jars=("$jar_dir"/*.jar)
shopt -u nullglob
(( ${#jars[@]} > 0 )) || fail "Artifact resolution produced no jars in $jar_dir"

# The lock records what the build system chose, with checksums, so the image
# contents can be audited without rebuilding it.
# Not --quiet: dependency:list writes the coordinates on INFO lines, which
# quiet mode suppresses entirely.
coordinates="$( (cd "$REPO_DIR" && ./mvnw --batch-mode --file platform/spark/image/pom.xml \
  dependency:list -DincludeScope=runtime 2>/dev/null) \
  | sed -nE 's/^\[INFO\] +([a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+:jar:[0-9][^ :]*):?.*$/\1/p' | sort -u || true)"

{
  printf '# Stratus Spark runtime image artifact lock\n'
  printf '# Generated by scripts/lib/spark-compose-resolve-artifacts.sh\n'
  printf '# Base image: %s\n' "$SPARK_BASE_IMAGE"
  printf '#\n'
  printf '# Maven coordinates, from which each artifact licence is resolvable:\n'
  if [[ -n "$coordinates" ]]; then
    printf '#   %s\n' $coordinates
  else
    printf '#   (coordinate listing unavailable; see platform/spark/image/pom.xml)\n'
  fi
  printf '#\n'
  printf '# sha256  filename\n'
  for jar in "${jars[@]}"; do
    printf '%s  %s\n' "$(sha256sum "$jar" | cut -d' ' -f1)" "$(basename "$jar")"
  done
} >"$lock_file"

log "Locked ${#jars[@]} artifacts into $jar_dir"
log "Lock manifest: $lock_file"
log "Build the image with: docker build -f platform/spark/image/Dockerfile -t $SPARK_IMAGE platform/spark/image"
